export enum HTTPMESSAGE {
    SUCCESS="success",
    FAILED="failed",
    UNOTFOUND="user not found !",
    PASSNOTMATCH="password does not match",
    UCONNECTED="user already connected",
    MAILUND="email undefined",
    DRAWINGEXIST="drawing already exists",
    ROOMEXIST="room already exists",
    ALBUMEXIST="album already exist",
    RNOTFOUND="room not found",
    ANOTFOUND="album not found",
    DNOTFOUND="drawing not found",
    UNOPERMISSION="user does not have permission",
    UNOTMEMBER="user is not a member",
    UISOWNER="user is owner",
    REQNOTFOUND="request not found",
    UALREADYLIKE="user already liked",
    FNOTFOUND="friend not found",
    ALREADYF="already friends",
    DNOTPROTECTED="drawing is not protected"
}
